#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Makes dongs.
"""

__author__ = 'Jathan McCollum, Mark Ellzey Thomas'
__maintainer__ = 'Jathan McCollum'
__email__ = 'jathan@gmail.com'
__copyright__ = '2009-2013, Jathan McCollum'
__version__ = '5.0'
import os
import sys
import random

MAXLEN = 40


def mkdong(length):
    """Pring a dong of ``length`` length."""
    if donglen > MAXLEN:
        sys.exit('warning: a %s" dong is too big! cannot be longer than %s"!' %
                (donglen, MAXLEN))
    else:
        dong = []
        dong.append('( )/( )')
        for i in range(donglen):
            dong[0]+='/'
        dong[0] += 'D'

    return dong

def mklongdong(length):
    """Pring a dong of ``length`` length."""
    if donglen > MAXLEN:
        sys.exit('warning: a %s" longdong is too big! cannot be longer than %s"!' %
                (longdonglen, MAXLEN))
    else:
        longdong = []
        longdong.append('   /\ ')
        for i in range(donglen): #veins
            #not 1 in 3 chances, gets recalced every check
            if random.randint(0, 10) in (2, 3, 4):
                longdong.append('  |\' |  ')
            elif random.randint(0, 10) in (5, 6, 7):
                longdong.append('  | \'|  ')
            elif random.randint(0, 10) in (8, 9, 10):
                longdong.append('  |\'\'|  ')
            else:
                longdong.append('  |  |  ')
        longdong.append(' / \/ \\ ')
        longdong.append(' \ /\ / ')

    return longdong

if __name__ == '__main__':
    try:
        donglen = int(sys.argv[1])
        if len(sys.argv) == 3:
            if sys.argv[2] == "--long":
                dong = mklongdong(donglen)
        else:
            dong = mkdong(donglen)

    except Exception, e:
        sys.exit("usage: mkdong <length> [--long]")

    for d in dong:
        os.system('echo "%s"' % d)
